### PR TITLE
Expand the help text for the start command, and give a hint on where …

### PR DESCRIPTION
**Pull request by tomwhoiscontrary**
…to find it (#98)

How does this look?

### CODE REVIEW

**Comment by ddollar** [comment]
Can you please bump your PR to kick off Circle CI again?

**Comment by ddollar** [comment]
Made some changes to the release script so a rebase should kick off CI here once you're ready.

**Comment by tomwhoiscontrary** [comment]
I think it got bumped. However, it doesn't look like Circle CI ran for this PR: https://circleci.com/gh/ddollar/forego

Am i doing it wrong?

**Comment by ddollar** [comment]
Thanks!

**Pull request merged**
